language: go

go:
  - 1.9
  - master

install:
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
  - go get github.com/OktaSecurityLabs/sgt
 
script:
  - go vet
  - go build
