language: go

go:
  - 1.9
  - master

before_install:
  - mv ../../OktaSecurityLabs ../../oktasecuritylabs

install:
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"

script:
  - go vet
  - go test -v ./...
  - go build
